### ISSUE TITLE
npm ERR

### ISSUE THREAD

**Issue by PortableTomb** [pluralsight-styling-angular-apps/demos#1]
Hi, I cloned this repo and npm installed to run this tutorial and this fails on my system:
npm ERR!     tsc && concurrently "npm run scss" "npm run scss:w" "tsc -w" "lite-server"

**Comment by brianmtreese** [comment]
Thanks for pointing this out! This should be fixed now, let me know if you run into any more issues.

**Comment by pedy711** [comment]
npm install also didn't run successfully on my machine. It seems that this project requires python to build. Is that right?
